language: generic

# Anytime we're making use of Docker, we need superuser level permission
sudo: required

services:
  # informs Travis that we need a copy of Docker ready to go
  - docker

# series of commands that's going to be executed before our tests are ran
before_install:
  - docker build -t zhidong32142/docker-react -f Dockerfile.dev .


script:
  # CI=true forces Jest to run in CI-mode, which will only run the test once
  # rather than launching the watcher
  # each '-e' allows us to set an environment variable (CI in this case)
  - docker run -e CI=true zhidong32142/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-107147372111"
  # project folder will only be created after first deploy, hence we need to use the app name 
  # as placeholder when doing initial deployment
  bucket_path: "docker-react"
  on:
    # Only deploy when merging to master
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

